import pygame as pg

TURRET_DATA = {
    "archer": [
        {
        "range": 175,
        "cooldown": 2000,
        "damage": 20,
        "damage_type": "ranged",
        "effect": [],
        "num_of_targets_hit": 1,
        "cost": 15,
        "upgrade_cost": 75,
        "image": 'assets\\towers\\archer0.png',
        "projectile_image": 'assets\\projectiles\\archer_proj0.png',
        "projectile_speed": 6,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\arrow0.wav'
        },
        {
        "range": 200,
        "cooldown": 1900,
        "damage": 45,
        "damage_type": "ranged",
        "effect": [],
        "num_of_targets_hit": 1,
        "upgrade_cost": 150,
        "image": 'assets\\towers\\archer1.png',
        "projectile_image": 'assets\\projectiles\\archer_proj0.png',
        "projectile_speed": 6,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\arrow0.wav'
        },
        {
        "range": 250,
        "cooldown": 1800,
        "damage": 75,
        "damage_type": "ranged",
        "effect": [],
        "num_of_targets_hit": 1,
        "upgrade_cost": 200,
        "image": 'assets\\towers\\archer2.png',
        "projectile_image": 'assets\\projectiles\\archer_proj0.png',
        "projectile_speed": 6,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\arrow0.wav'
        },
        {
        "range": 300,
        "cooldown": 1700,
        "damage": 175,
        "damage_type": "ranged",
        "effect": [],
        "num_of_targets_hit": 1,
        "upgrade_cost": 400,
        "image": 'assets\\towers\\archer3.png',
        "projectile_image": 'assets\\projectiles\\archer_proj0.png',
        "projectile_speed": 6,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\arrow0.wav'
        },
        {
        "range": 350,
        "cooldown": 1400,
        "damage": 250,
        "damage_type": "ranged",
        "effect": [],
        "num_of_targets_hit": 1,
        "upgrade_cost": 0,
        "image": 'assets\\towers\\archer4.png',
        "projectile_image": 'assets\\projectiles\\archer_proj0.png',
        "projectile_speed": 6,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\arrow0.wav'
        }
    ],
    "crossbowman" : [
        {
        "range": 250,
        "cooldown": 2500,
        "damage": 50,
        "damage_type": "pierce",
        "effect": ["armor_pen"],
        "num_of_targets_hit": 1,
        "cost": 25,
        "upgrade_cost": 100,
        "image": 'assets\\towers\\cbm0.png',
        "projectile_image": 'assets\\projectiles\\cbm_proj0.png',
        "projectile_speed": 8,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\crossbow0.wav'
        },
        {
        "range": 275,
        "cooldown": 2300,
        "damage": 90,
        "damage_type": "pierce",
        "effect": ["armor_pen"],
        "num_of_targets_hit": 1,
        "upgrade_cost": 200,
        "image": 'assets\\towers\\cbm1.png',
        "projectile_image": 'assets\\projectiles\\cbm_proj0.png',
        "projectile_speed": 8,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\crossbow0.wav'
        },
        {
        "range": 300,
        "cooldown": 2100,
        "damage": 150,
        "damage_type": "pierce",
        "effect": ["armor_pen"],
        "num_of_targets_hit": 1,
        "upgrade_cost": 300,
        "image": 'assets\\towers\\cbm2.png',
        "projectile_image": 'assets\\projectiles\\cbm_proj0.png',
        "projectile_speed": 8,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\crossbow0.wav'
        },
        {
        "range": 325,
        "cooldown": 1900,
        "damage": 300,
        "damage_type": "pierce",
        "effect": ["armor_pen"],
        "num_of_targets_hit": 1,
        "upgrade_cost": 500,
        "image": 'assets\\towers\\cbm3.png',
        "projectile_image": 'assets\\projectiles\\cbm_proj0.png',
        "projectile_speed": 8,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\crossbow0.wav'
        },
        {
        "range": 325,
        "cooldown": 1900,
        "damage": 400,
        "damage_type": "pierce",
        "effect": ["armor_pen"],
        "num_of_targets_hit": 1,
        "upgrade_cost": 0,
        "image": 'assets\\towers\\cbm4.png',
        "projectile_image": 'assets\\projectiles\\cbm_proj0.png',
        "projectile_speed": 8,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\crossbow0.wav'
        }
    ],
    "melee" : [
        {
        "range": 175,
        "cooldown": 800,
        "damage": 20,
        "damage_type": "slash",
        "effect": ["dmg_over_time"],
        "num_of_targets_hit": 1,
        "cost": 20,
        "upgrade_cost": 100,
        "image": 'assets\\towers\\melee0.png',
        "projectile_image": 'assets\\projectiles\\melee_proj0.png',
        "projectile_speed": 25,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\melee0.wav'
        },
        {
        "range": 175,
        "cooldown": 700,
        "damage": 25,
        "damage_type": "slash",
        "effect": ["dmg_over_time"],
        "num_of_targets_hit": 1,
        "upgrade_cost": 200,
        "image": 'assets\\towers\\melee1.png',
        "projectile_image": 'assets\\projectiles\\melee_proj0.png',
        "projectile_speed": 25,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\melee0.wav'
        },
        {
        "range": 175,
        "cooldown": 500,
        "damage": 30,
        "damage_type": "slash",
        "effect": ["dmg_over_time"],
        "num_of_targets_hit": 1,
        "upgrade_cost": 300,
        "image": 'assets\\towers\\melee2.png',
        "projectile_image": 'assets\\projectiles\\melee_proj0.png',
        "projectile_speed": 25,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\melee0.wav'
        },
        {
        "range": 175,
        "cooldown": 300,
        "damage": 40,
        "damage_type": "slash",
        "effect": ["dmg_over_time"],
        "num_of_targets_hit": 1,
        "upgrade_cost": 500,
        "image": 'assets\\towers\\melee3.png',
        "projectile_image": 'assets\\projectiles\\melee_proj0.png',
        "projectile_speed": 25,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\melee0.wav'
        },
        {
        "range": 200,
        "cooldown": 100,
        "damage": 55,
        "damage_type": "slash",
        "effect": ["dmg_over_time"],
        "num_of_targets_hit": 2,
        "upgrade_cost": 0,
        "image": 'assets\\towers\\melee4.png',
        "projectile_image": 'assets\\projectiles\\melee_proj0.png',
        "projectile_speed": 25,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\melee0.wav'
        }
    ],
    "siege": [
        {
        "range": 275,
        "cooldown": 3000,
        "damage": 90,
        "damage_type": "heavy",
        "effect": ["stun"],
        "num_of_targets_hit": 1,
        "cost": 50,
        "upgrade_cost": 100,
        "image": 'assets\\towers\\siege0.png',
        "projectile_image": 'assets\\projectiles\\siege_proj0.png',
        "projectile_speed": 6,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\siege0.wav'
        },
        {
        "range": 275,
        "cooldown": 3500,
        "damage": 70,
        "damage_type": "heavy",
        "effect": ["stun"],
        "num_of_targets_hit": 3,
        "upgrade_cost": 200,
        "image": 'assets\\towers\\siege1.png',
        "projectile_image": 'assets\\projectiles\\siege_proj0.png',
        "projectile_speed": 6,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\siege0.wav'
        },
        {
        "range": 350,
        "cooldown": 3000,
        "damage": 250,
        "damage_type": "heavy",
        "effect": ["stun"],
        "num_of_targets_hit": 2,
        "upgrade_cost": 400,
        "image": 'assets\\towers\\siege2.png',
        "projectile_image": 'assets\\projectiles\\siege_proj2.png',
        "projectile_speed": 6,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\siege0.wav'
        },
        {
        "range": 350,
        "cooldown": 3200,
        "damage": 300,
        "damage_type": "heavy",
        "effect": ["stun"],
        "num_of_targets_hit": 4,
        "upgrade_cost": 800,
        "image": 'assets\\towers\\siege3.png',
        "projectile_image": 'assets\\projectiles\\siege_proj2.png',
        "projectile_speed": 6,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\siege0.wav'
        },
        {
        "range": 350,
        "cooldown": 2000,
        "damage": 450,
        "damage_type": "heavy",
        "effect": ["stun"],
        "num_of_targets_hit": 2,
        "upgrade_cost": 0,
        "image": 'assets\\towers\\siege4.png',
        "projectile_image": 'assets\\projectiles\\siege_proj4.png',
        "projectile_speed": 6,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\siege0.wav'
        }
    ],
    "sniper" : [
        {
        "range": 310,
        "cooldown": 3000,
        "damage": 200,
        "damage_type": "pierce",
        "effect": ["armor_pen"],
        "num_of_targets_hit": 1,
        "cost": 25,
        "upgrade_cost": 75,
        "image": 'assets\\towers\\sniper0.png',
        "projectile_image": 'assets\\projectiles\\sniper_proj0.png',
        "projectile_speed": 11,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\sniper0.wav'
        },
        {
        "range": 420,
        "cooldown": 2800,
        "damage": 250,
        "damage_type": "pierce",
        "effect": ["armor_pen"],
        "num_of_targets_hit": 1,
        "upgrade_cost": 125,
        "image": 'assets\\towers\\sniper1.png',
        "projectile_image": 'assets\\projectiles\\sniper_proj0.png',
        "projectile_speed": 12,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\sniper0.wav'
        },
        {
        "range": 530,
        "cooldown": 2600,
        "damage": 350,
        "damage_type": "pierce",
        "effect": ["armor_pen"],
        "num_of_targets_hit": 1,
        "upgrade_cost": 200,
        "image": 'assets\\towers\\sniper2.png',
        "projectile_image": 'assets\\projectiles\\sniper_proj0.png',
        "projectile_speed": 13,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\sniper0.wav'
        },
        {
        "range": 640,
        "cooldown": 2500,
        "damage": 500,
        "damage_type": "pierce",
        "effect": ["armor_pen"],
        "num_of_targets_hit": 1,
        "upgrade_cost": 500,
        "image": 'assets\\towers\\sniper3.png',
        "projectile_image": 'assets\\projectiles\\sniper_proj0.png',
        "projectile_speed": 14,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\sniper0.wav'
        },
        {
        "range": 750,
        "cooldown": 1800,
        "damage": 750,
        "damage_type": "pierce",
        "effect": ["armor_pen"],
        "num_of_targets_hit": 1,
        "upgrade_cost": 0,
        "image": 'assets\\towers\\sniper4.png',
        "projectile_image": 'assets\\projectiles\\sniper_proj0.png',
        "projectile_speed": 15,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\sniper0.wav'
        }
    ],
    "fire" : [
        {
        "range": 175,
        "cooldown": 1000,
        "damage": 15,
        "damage_type": "fire",
        "effect": ["dmg_over_time"],
        "num_of_targets_hit": 2,
        "cost": 25,
        "upgrade_cost": 70,
        "image": 'assets\\towers\\fire0.png',
        "projectile_image": 'assets\\projectiles\\fire_proj0.png',
        "projectile_speed": 6,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\fire0.wav'
        },
        {
        "range": 200,
        "cooldown": 1000,
        "damage": 20,
        "damage_type": "fire",
        "effect": ["dmg_over_time"],
        "num_of_targets_hit": 3,
        "upgrade_cost": 125,
        "image": 'assets\\towers\\fire1.png',
        "projectile_image": 'assets\\projectiles\\fire_proj0.png',
        "projectile_speed": 6,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\fire0.wav'
        },
        {
        "range": 225,
        "cooldown": 800,
        "damage": 30,
        "damage_type": "fire",
        "effect": ["dmg_over_time"],
        "num_of_targets_hit": 4,
        "upgrade_cost": 250,
        "image": 'assets\\towers\\fire2.png',
        "projectile_image": 'assets\\projectiles\\fire_proj0.png',
        "projectile_speed": 6,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\fire0.wav'
        },
        {
        "range": 250,
        "cooldown": 600,
        "damage": 50,
        "damage_type": "fire",
        "effect": ["dmg_over_time"],
        "num_of_targets_hit": 5,
        "upgrade_cost": 500,
        "image": 'assets\\towers\\fire3.png',
        "projectile_image": 'assets\\projectiles\\fire_proj0.png',
        "projectile_speed": 6,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\fire0.wav'
        },
        {
        "range": 275,
        "cooldown": 500,
        "damage": 100,
        "damage_type": "fire",
        "effect": ["dmg_over_time"],
        "num_of_targets_hit": 6,
        "upgrade_cost": 0,
        "image": 'assets\\towers\\fire4.png',
        "projectile_image": 'assets\\projectiles\\fire_proj0.png',
        "projectile_speed": 6,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\fire0.wav'
        },
    ],
    "frost" : [
        {
        "range": 175,
        "cooldown": 2000,
        "damage": 10,
        "damage_type": "frost",
        "effect": ["slow"],
        "num_of_targets_hit": 1,
        "cost": 25,
        "upgrade_cost": 75,
        "image": 'assets\\towers\\frost0.png',
        "projectile_image": 'assets\\projectiles\\frost_proj0.png',
        "projectile_speed": 5,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\frost0.wav'
        },
        {
        "range": 175,
        "cooldown": 1900,
        "damage": 15,
        "damage_type": "frost",
        "effect": ["slow"],
        "num_of_targets_hit": 2,
        "upgrade_cost": 125,
        "image": 'assets\\towers\\frost1.png',
        "projectile_image": 'assets\\projectiles\\frost_proj0.png',
        "projectile_speed": 6,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\frost0.wav'
        },
        {
        "range": 200,
        "cooldown": 1800,
        "damage": 25,
        "damage_type": "frost",
        "effect": ["slow"],
        "num_of_targets_hit": 3,
        "upgrade_cost": 250,
        "image": 'assets\\towers\\frost2.png',
        "projectile_image": 'assets\\projectiles\\frost_proj0.png',
        "projectile_speed": 7,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\frost0.wav'
        },
        {
        "range": 225,
        "cooldown": 1500,
        "damage": 80,
        "damage_type": "frost",
        "effect": ["slow"],
        "num_of_targets_hit": 4,
        "upgrade_cost": 500,
        "image": 'assets\\towers\\frost3.png',
        "projectile_image": 'assets\\projectiles\\frost_proj0.png',
        "projectile_speed": 7,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\frost0.wav'
        },
        {
        "range": 275,
        "cooldown": 1200,
        "damage": 200,
        "damage_type": "frost",
        "effect": ["slow"],
        "num_of_targets_hit": 5,
        "upgrade_cost": 0,
        "image": 'assets\\towers\\frost4.png',
        "projectile_image": 'assets\\projectiles\\frost_proj0.png',
        "projectile_speed": 8,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\frost0.wav'
        },
    ],
    "poison" : [
        {
        "range": 175,
        "cooldown": 1500,
        "damage": 20,
        "damage_type": "poison",
        "effect": ["slow", "dmg_over_time"],
        "num_of_targets_hit": 1,
        "cost": 15,
        "upgrade_cost": 50,
        "image": 'assets\\towers\\poison0.png',
        "projectile_image": 'assets\\projectiles\\poison_proj0.png',
        "projectile_speed": 10,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\poison0.wav'
        },
        {
        "range": 200,
        "cooldown": 1400,
        "damage": 25,
        "damage_type": "poison",
        "effect": ["slow", "dmg_over_time"],
        "num_of_targets_hit": 1,
        "upgrade_cost": 100,
        "image": 'assets\\towers\\poison1.png',
        "projectile_image": 'assets\\projectiles\\poison_proj0.png',
        "projectile_speed": 10,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\poison0.wav'
        },
        {
        "range": 250,
        "cooldown": 1300,
        "damage": 40,
        "damage_type": "poison",
        "effect": ["slow", "dmg_over_time"],
        "num_of_targets_hit": 1,
        "upgrade_cost": 200,
        "image": 'assets\\towers\\poison2.png',
        "projectile_image": 'assets\\projectiles\\poison_proj0.png',
        "projectile_speed": 10,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\poison0.wav'
        },
        {
        "range": 275,
        "cooldown": 1200,
        "damage": 80,
        "damage_type": "poison",
        "effect": ["slow", "dmg_over_time"],
        "num_of_targets_hit": 1,
        "upgrade_cost": 400,
        "image": 'assets\\towers\\poison3.png',
        "projectile_image": 'assets\\projectiles\\poison_proj0.png',
        "projectile_speed": 10,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\poison0.wav'
        },
        {
        "range": 300,
        "cooldown": 800,
        "damage": 200,
        "damage_type": "poison",
        "effect": ["slow", "dmg_over_time"],
        "num_of_targets_hit": 1,
        "upgrade_cost": 0,
        "image": 'assets\\towers\\poison4.png',
        "projectile_image": 'assets\\projectiles\\poison_proj0.png',
        "projectile_speed": 10,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\poison0.wav'
        },
    ],
    "electric" : [
        {
        "range": 175,
        "cooldown": 2000,
        "damage": 10,
        "damage_type": "electric",
        "effect": ["stun", "armor_pen"],
        "num_of_targets_hit": 1,
        "cost": 50,
        "upgrade_cost": 100,
        "image": 'assets\\towers\\electric0.png',
        "projectile_image": 'assets\\projectiles\\electric_proj0.png',
        "projectile_speed": 8,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\electric0.wav'
        },
        {
        "range": 200,
        "cooldown": 1950,
        "damage": 15,
        "damage_type": "electric",
        "effect": ["stun", "armor_pen"],
        "num_of_targets_hit": 2,
        "upgrade_cost": 200,
        "image": 'assets\\towers\\electric1.png',
        "projectile_image": 'assets\\projectiles\\electric_proj0.png',
        "projectile_speed": 8,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\electric0.wav'
        },
        {
        "range": 250,
        "cooldown": 1900,
        "damage": 30,
        "damage_type": "electric",
        "effect": ["stun", "armor_pen"],
        "num_of_targets_hit": 3,
        "upgrade_cost": 400,
        "image": 'assets\\towers\\electric2.png',
        "projectile_image": 'assets\\projectiles\\electric_proj0.png',
        "projectile_speed": 8,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\electric0.wav'
        },
        {
        "range": 300,
        "cooldown": 1850,
        "damage": 60,
        "damage_type": "electric",
        "effect": ["stun", "armor_pen"],
        "num_of_targets_hit": 4,
        "upgrade_cost": 800,
        "image": 'assets\\towers\\electric3.png',
        "projectile_image": 'assets\\projectiles\\electric_proj0.png',
        "projectile_speed": 8,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\electric0.wav'
        },
        {
        "range": 325,
        "cooldown": 1500,
        "damage": 80,
        "damage_type": "electric",
        "effect": ["stun", "armor_pen"],
        "num_of_targets_hit": 5,
        "upgrade_cost": 0,
        "image": 'assets\\towers\\electric4.png',
        "projectile_image": 'assets\\projectiles\\electric_proj0.png',
        "projectile_speed": 10,
        "projectile_sfx": 'assets\\audio\\projectileSFX\\electric0.wav'
        },
    ]
}